### PR TITLE
add ability to specify loadBalancerIP and loadBalancerSourceRanges on Service configuration

### PR DESCRIPTION
**Pull request by Romain7495**
Hi,

I would like to add loadBalancerIP, and loadBalancerSourceRanges in your helm chart.

I hope that it will be accepted :) 

Signed-off-by: Romain Labat <contact@romainlabat.fr>

### CODE REVIEW

**Comment by bagl3y** [comment]
That would be great indeed !

**Comment by tananaev** [comment]
Traccar doesn't currently support horizontal scaling. What would be the point of load balancer in this case.

By the way, we are working on allowing scaling.

**Comment by Romain7495** [comment]
I need a unique ip for traccar, I will not deploy an ingress controller only for traccar, and I am sure, I am not the only one 

Btw, the helm chart is bot supporting ingress as well

The PR goal is juste to be more generic, and I know that we cannot scale horizontally for now

**Comment by tananaev** [comment]
Cool. I'm not really an expert in helm charts. @kondas can you review this please.

**Review by kondas — APPROVED** [review]
Nice work, thanks!

**Comment by tananaev** [comment]
Merged, thank you.

**Pull request merged**
