### PR TITLE
various configmap fixes

### PR DESCRIPTION
**Pull request by filippolmt**

### CODE REVIEW

**Comment by tananaev** [comment]
Looks like some checks are failing.

**Comment by filippolmt** [comment]
the problem should be in the persistent volume of mysql, of course in the second commit I wrote it wrong .... -_-'

**Comment by filippolmt** [comment]
the problem was in the configmap and how I configured logger.

I don't know if you like how I fixed the values, my idea is to uncomment the values ​​as much as possible and to set the attributes.

I noticed that if logged is set to false the container fails to write logs, in my opinion by default it should write to stdout and should not be configurable.

**Comment by tananaev** [comment]
Merged, thanks.

**Comment by tananaev** [comment]
@filippolmt looks like CI failed after merge.

**Pull request merged**
