### PR TITLE
Add chart v1.0.1

### PR DESCRIPTION
**Pull request by filippolmt**
I created the release, in case we can't automate it all? @tananaev @kondas

### CODE REVIEW

**Comment by filippolmt** [comment]
Yes, of course, you could use the github actions to do everything, the workflow could be the following:

if a new branch is created and changes are made, an action is triggered that carries out all the checks (lint, apply of the chart, etc.)

When a merge is performed in main and the release is tagged, an action is automatically triggered to create the helm release.

**Comment by tananaev** [comment]
Would you be able to set up a GitHub action for us?

**Comment by filippolmt** [comment]
I created an action for packer and terraform, I don't think there are any problems creating it for helm. I am willing to help you and create the action.

**Comment by tananaev** [comment]
Awesome, thank you.

**Pull request closed without merging**
