### PR TITLE
Added extra notification config fields

### PR DESCRIPTION
**Pull request by ricklambrechts**
According to the docs: https://www.traccar.org/documentation/notifications/

### CODE REVIEW

**Comment by ricklambrechts** [comment]
I can't find the reason that the linter fails

**Comment by ricklambrechts** [comment]
Yes, but which version. The chart version? Or the appVersion?

**Comment by ricklambrechts** [comment]
Thanks, found it! Should i rebase and use version 1.1.4? Or is this version number ok for you?

**Comment by tananaev** [comment]
I think it's ok.

**Pull request merged**
