### PR TITLE
security context to init container

### PR DESCRIPTION
**Pull request by lomas969**
Add security context to init container so that it works on RKE2 which has a restricted cluster wide psp blocking root user.

### CODE REVIEW

**Comment by tananaev** [comment]
Can you provide a bit more details on what this does.

**Comment by lomas969** [comment]
Hi
I've been meaning to try this system out on the cluster I'm running at home, which is installed with RKE2.
RKE2 comes with a global pod security policy that won't let any container run as root on any namespace besides kube-system and default.
All I did was copying the pod security lines from the traccar container to the init container so that this latter one starts as a nonRoot user and is allowed to run on RKE2.
(this is my first ever pull request)

**Comment by tananaev** [comment]
@kondas can you please check this PR.

**Comment by kondas** [comment]
@lomas969 Thanks for the contribution, this is definately useful. @tananaev Please go on with the merge Ps. sorry that it took so long :)

**Pull request merged**
